### ISSUE TITLE
hnix-store-core-0.8.0.0 fails to build with crypton-1.1 and ram

### ISSUE THREAD

**Issue by juhp** [haskell-nix/hnix-store#317]
```
       Building library for hnix-store-core-0.8.0.0...
       [ 1 of 15] Compiling System.Nix.Base32
       [ 2 of 15] Compiling System.Nix.Base
       [ 3 of 15] Compiling System.Nix.Hash.Truncation
       [ 4 of 15] Compiling System.Nix.Hash
       /home/curators/work/unpack-dir/unpacked/hnix-store-core-0.8.0.0-4ec04ed6fca38f58a77a60cebe2bade88618becd43d3c603e3afa775b5646bae/src/System/Nix/Hash.hs:151:5: error: [GHC-39999]
           • Could not deduce ‘Data.ByteArray.ByteArrayAccess (Digest a)’
               arising from a use of ‘Data.ByteArray.convert’
             from the context: HashAlgorithm a
               bound by the type signature for:
                          mkStorePathHash :: forall a.
                                             HashAlgorithm a =>
                                             ByteString -> ByteString
               at src/System/Nix/Hash.hs:(144,1)-(148,15)
           • In the first argument of ‘($)’, namely ‘Data.ByteArray.convert’
             In the second argument of ‘($)’, namely
               ‘Data.ByteArray.convert $ Crypto.Hash.hash @ByteString @a bs’
             In the expression:
               System.Nix.Hash.Truncation.truncateInNixWay 20
                 $ Data.ByteArray.convert $ Crypto.Hash.hash @ByteString @a bs
           |
       151 |   $ Data.ByteArray.convert
           |     ^^^^^^^^^^^^^^^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/hnix-store-core-0.8.0.0-4ec04ed6fca38f58a77a60cebe2bade88618becd43d3c603e3afa775b5646bae/src/System/Nix/Hash.hs:156:53: error: [GHC-39999]
           • No instance for ‘Data.ByteArray.ByteArrayAccess (Digest a)’
               arising from a use of ‘Data.ByteArray.convert’
           • In the second argument of ‘(.)’, namely ‘Data.ByteArray.convert’
             In the expression:
               System.Nix.Base.encodeWith b . Data.ByteArray.convert
             In an equation for ‘encodeDigestWith’:
                 encodeDigestWith b
                   = System.Nix.Base.encodeWith b . Data.ByteArray.convert
           |
       156 | encodeDigestWith b = System.Nix.Base.encodeWith b . Data.ByteArray.convert
           |                                                     ^^^^^^^^^^^^^^^^^^^^^^

       [ 5 of 15] Compiling System.Nix.Signature
       /home/curators/work/unpack-dir/unpacked/hnix-store-core-0.8.0.0-4ec04ed6fca38f58a77a60cebe2bade88618becd43d3c603e3afa775b5646bae/src/System/Nix/Signature.hs:53:22: error: [GHC-39999]
           • No instance for ‘Data.ByteArray.ByteArrayAccess
                                Ed25519.Signature’
               arising from a use of ‘Data.ByteArray.convert’
           • In the second argument of ‘encodeWith’, namely
               ‘(Data.ByteArray.convert sig :: ByteString)’
             In the expression:
               encodeWith Base64 (Data.ByteArray.convert sig :: ByteString)
             In an equation for ‘signatureToText’:
                 signatureToText (Signature sig)
                   = encodeWith Base64 (Data.ByteArray.convert sig :: ByteString)
          |
       53 |   encodeWith Base64 (Data.ByteArray.convert sig :: ByteString)
          |                      ^^^^^^^^^^^^^^^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/hnix-store-core-0.8.0.0-4ec04ed6fca38f58a77a60cebe2bade88618becd43d3c603e3afa775b5646bae/src/System/Nix/Signature.hs:66:11: error: [GHC-39999]
           • No instance for ‘Data.ByteArray.ByteArrayAccess
                                Ed25519.Signature’
               arising from a use of ‘Data.ByteArray.convert’
           • In the expression: Data.ByteArray.convert x :: ByteString
             In an equation for ‘xBS’:
                 xBS = Data.ByteArray.convert x :: ByteString
             In the expression:
               let
                 xBS = Data.ByteArray.convert x :: ByteString
                 yBS = Data.ByteArray.convert y :: ByteString
               in compare xBS yBS
          |
       66 |     xBS = Data.ByteArray.convert x :: ByteString
          |           ^^^^^^^^^^^^^^^^^^^^^^
```
