### ISSUE TITLE
hnix-store-core fails to build with GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix-store#142]
…when I use `--allow-newer=base` to circumvent the bounds in the `cryptohash-` packages:

```
src/System/Nix/ReadonlyStore.hs:60:12: error:
    • Syntax error on 'SHA256
      Perhaps you intended to use TemplateHaskell or TemplateHaskellQuotes
    • In the Template Haskell quotation 'SHA256
   |
60 |     hash @ 'SHA256
   |            ^^^^^^^

<no location info>: warning: [-Wunused-packages]
    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - nix-derivation-1.1.1
```

Not sure what the warning regarding `nix-derivation` is about…

**Comment by sjakobi** [comment]
The syntax error _might_ be related to https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#whitespace-sensitive-and-

**Comment by Anton-Latukha** [comment]
Would keep it open, until migrated away from `cryptohash-*` (currently working on it).

Additional raw anecdote is - https://packdeps.haskellers.com/reverse/cryptohash-sha256 has `cabal-install`.

**Comment by Anton-Latukha** [comment]
@sjakobi In #157 the migration to `cryptonite` happened. As a useful side-effect the `hnis-store-core` not support GHC 9.0. & release of 0.5 was made. So closing this one. Further the support of GHC 9.0 for HNix.

**Comment by sjakobi** [comment]
Nice progress, @Anton-Latukha! :muscle: :smile:
